version: "3"
services:
  app:
    build:
      context: "docker/app/"
    ports:
      - 80:80
    working_dir: /var/www/public
    volumes:
      - "./www/:/var/www"
      - "./docker/app/httpd.conf:/etc/httpd/conf/httpd.conf"
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    build:
      context: "docker/mysql/"
    environment:
      - MYSQL_DATABASE=wow
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=gpol1515
      - TZ=Asia/Tokyo
    volumes:
      - "./docker/mysql/storage/:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=gpol1515
    depends_on:
      - mysql
volumes:
  storage: